name: continuous-integration
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Test
      env:
        GROUPME_TOKEN: ${{ secrets.GROUPME_TOKEN }}
      run: go test ./test/...
